spring:
  application:
    name: order-service
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.107.99.176:3306/microservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml  # 这里一定需要注意
  type-handlers-package: com.gxu.sp04.typehandler

server:
  port: 8083
